title: Logan Rules
baseURL: https://loganrules.net/
theme: hugo-resume
languageCode: en-us
PygmentsCodeFences: true
PygmentsCodeFencesGuessSyntax: true
PygmentsStyle: monokai
enableGitInfo: false
params:
  address: Clarksville, OH
  email: ljsneed11@gmail.com
  favicon: /favicon.ico
  firstName: Logan
  lastName: Sneed
  phone: 1-513-614-1513
  profileImage: /Logo.png
  showQr: true
  showContact: false
  showBoards: false
  showCertifications: false
  showSocializations: true
  sections:
  - Youtube
  - education
  - 3d_printing
  - my_tech
  - Games
  google:
    analytics:
      trackerID: XX-123446-01
  handles:
  - name: Youtube
    link: https://www.youtube.com/@logan_sneed/
  - name: GitHub
    link: https://github.com/ljs2311/
  - name: Reddit
    link: https://www.reddit.com/user/Rare-Perspective-474/
  - name: Amazon Music
    link: https://music.amazon.com/profiles/g47jxp4h5mwzjagfhanzjpzzfu
outputs:
  home:
  - HTML
  - JSON
taxonomies:
  tag: tags
markup:
  goldmark:
    renderer:
      unsafe: true
